package com.threeamigos.foresta.eventi;

/**
 *
 * @author Stefano Reksten
 */
public enum TipoEvento {

    MESSAGGIO,
    FUMETTO,
    NOTIFICA_GLOBALE,

    RICHIESTA_SPOSTAMENTO_OGGETTO,
    APPROVAZIONE_SPOSTAMENTO_OGGETTO,
    RIFIUTO_SPOSTAMENTO_OGGETTO,

    PERSONAGGIO_CREAZIONE,
    PERSONAGGIO_VARIAZIONE_STATO_VITALE,
    PERSONAGGIO_VARIAZIONE_STATISTICHE,
    PERSONAGGIO_VARIAZIONE_EFFETTO_DI_STATO,
    PERSONAGGIO_AGGIUNTA_MODIFICATORE,
    PERSONAGGIO_CONSUMO_PUNTO_ABILITA,
    PERSONAGGIO_COMBATTIMENTO,
    PERSONAGGIO_INTERAZIONE_ELEMENTALE,

    /**
     * Un PNG prende una decisione
     */
    PERSONAGGIO_VALUTAZIONE,

    /**
     * Attività interna di pulizia cache dinamica immagini
     */
    PULIZIA_CACHE_IMMAGINI
}
