package com.threeamigos.foresta.tipi;

/**
 * Le classi concrete di missione: l'identificativo con cui il modello dati (MissioneMD) dichiara il tipo di ogni nodo
 * dell'albero delle missioni, così che la ricostruzione dopo un caricamento sia polimorfica. La missione vera la
 * costruisce missioni.FabbricaMissioni. (Da non confondere con missioni.TipoMissione, le categorie di incarico.)
 */
public enum ClasseMissione {

	SCONFIGGI_IL_DRAGO,
	SCONFIGGI_IL_MINOTAURO_GIGANTE,
	SCONFIGGI_L_IDRA,
	SCONFIGGI_IL_LICH,
	SCONFIGGI_LA_STREGA,
	MISSIONE_DI_PROVA,
	MISSIONE_CHE_FALLISCE,
	RECUPERA_IL_MEDAGLIONE,
	RECUPERA_LE_DERRATE_ALIMENTARI,
	LA_LEGGENDA_DELL_ARMAIOLO,
	LA_LEGGENDA_DEL_LOCANDIERE,
	CRONACHE_DI_UN_FEGATO_EROICO,
	NESSUN_BOCCALE_LASCIATO_INDIETRO,
	DISTURBATORE_DELLA_QUIETE_PUBBLICA,
	CACCIA_AI_GOBLIN,
	RICHIESTA_ALCHIMISTA,
	RICHIESTA_ARMAIOLO,
	RICHIESTA_CAPITANO,
	RICHIESTA_LOCANDIERE,
	LA_TAGLIA_SULLA_BANDA,
	IL_PELLEGRINO,
	IL_RAPIMENTO,
	NON_SPARATE_SUL_PIANISTA,
	CACCIATORE_DI_TAGLIE,
	IL_CARTOGRAFO,
	IL_CORRIERE,
	L_OGGETTO_SMARRITO,
	INCARICO_DI_COMBATTIMENTO,
	LA_SORVEGLIANZA,
	IL_CONTRABBANDIERE,
	IL_SOCCORSO,
	L_INDAGINE,
	LA_BENEDIZIONE,
	IL_FAVORE,
	LA_LEALTA,
	IL_TORNEO,
	LA_DOCUMENTAZIONE,
	IL_COLPO,
	IL_RITUALE,

	MISSIONE_DI_PROVA_SECONDARIA_UNO,
	MISSIONE_DI_PROVA_SECONDARIA_DUE,
	MISSIONE_DI_PROVA_TERZIARIA_UNO,

	VISITA_LOCANDA,
	MUOVI_A_LOCAZIONE,
	MISSIONE_SECONDARIA;
}
